### ISSUE TITLE
Authentication and authorization (bonus)

### ISSUE THREAD

**Issue by alex-nexus** [mr-sudaca/yama#11]
1. How would you approach in general on authenticating the API requests?
2. How would you approach authorization, or determine who has the right or not the request certain APIs?

**Comment by mr-sudaca** [comment]
1. I added devise, devise_token_auth and grape_devise_token_auth gems to provide user login and authentication. User have to login and then provide access-token, client id, and uid (email) on each request in order to gain access, see https://github.com/mr-sudaca/yama/pull/16

2. Still working on this, I'll let you know when it's done

**Comment by alex-nexus** [comment]
ok

**Comment by alex-nexus** [comment]
please close when merged
